name: Fetch and Commit Transactions

on:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Fetch transactions
      run: node index.js

    - name: Commit changes
      run: |
        git config --local user.email "xwlyy1991@163.com"
        git config --local user.name "drafish"
        git add transactions.json
        if git diff --quiet --cached; then
          echo 'No changes to commit'
        else
          git commit -m 'Update transactions'
          git push
        fi
